CREATE TABLE `whale_addresses` (
  `address` varchar(45) DEFAULT NULL,
  `name` varchar(45) DEFAULT NULL,
  `twitter` varchar(256) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `bytecode_contracts` (
  `contract_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `owner_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `symbol` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `type` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `interface` tinyint(1) DEFAULT '0',
  `contract_uri` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `baseuri` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alert` int DEFAULT '0',
  `processed` int DEFAULT '0',
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `owner_ens` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`contract_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `mint_tracker_contracts` (
  `contract_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `block_number` int DEFAULT NULL,
  `contract_owner` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `baseuri` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `current_supply` decimal(26,6) DEFAULT '0.000000',
  `previous_supply` decimal(26,6) DEFAULT '0.000000',
  `delta_supply` decimal(26,6) DEFAULT '0.000000',
  `nft_type` varchar(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `interface` tinyint(1) DEFAULT '0',
  `tracking` tinyint(1) DEFAULT '0',
  `uri_retries` tinyint(1) DEFAULT '0',
  `opensea_retries` tinyint(1) DEFAULT '0',
  `retry_metadata_type` tinyint(1) DEFAULT '0',
  `image` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `token_uri` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `opensea_image_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `metadata_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `external_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_uri` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `standard_erc721` tinyint(1) DEFAULT '0',
  `bot` int DEFAULT '0',
  `minting` tinyint(1) DEFAULT '0',
  `owner_count` int DEFAULT '0',
  `metadata_updated` timestamp NULL DEFAULT NULL,
  `opensea_updated` timestamp NULL DEFAULT NULL,
  `last_mint` timestamp NULL DEFAULT NULL,
  `last_metadata_attempt` timestamp NULL DEFAULT NULL,
  `last_opensea_attempt` timestamp NULL DEFAULT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`contract_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `mint_tracker_txns` (
  `txn_id` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `block_number` int DEFAULT NULL,
  `method_id` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `minter_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_owner` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint DEFAULT '0',
  `bot` tinyint DEFAULT '0',
  `mints` int DEFAULT NULL,
  `average_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `ethervalue` decimal(33,21) DEFAULT '0.000000000000000000000',
  `txn_fee` decimal(33,21) DEFAULT '0.000000000000000000000',
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`txn_id`),
  KEY `block_idx` (`block_number`),
  KEY `status_date_idx` (`status`,`date`),
  KEY `minter_contract_idx` (`contract_address`,`minter_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mint_tracker_various_txns` (
  `txn_id` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `block_number` int DEFAULT NULL,
  `method_id` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `minter_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_owner` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint DEFAULT '0',
  `bot` tinyint DEFAULT '0',
  `mints` int DEFAULT NULL,
  `average_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `ethervalue` decimal(33,21) DEFAULT '0.000000000000000000000',
  `txn_fee` decimal(33,21) DEFAULT '0.000000000000000000000',
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`txn_id`),
  KEY `block_idx` (`block_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mint_tracker_whale_txns` (
  `txn_id` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `block_number` int DEFAULT NULL,
  `method_id` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `minter_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_owner` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint DEFAULT '0',
  `bot` tinyint DEFAULT '1',
  `mints` int DEFAULT NULL,
  `average_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `ethervalue` decimal(33,21) DEFAULT '0.000000000000000000000',
  `txn_fee` decimal(33,21) DEFAULT '0.000000000000000000000',
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`txn_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `settings` (
  `name` varchar(45) DEFAULT NULL,
  `setting` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `mint_tracker_alerts` (
  `contract_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_owner` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `token_uri` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `opensea_image_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `metadata_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `external_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_uri` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `current_mint` bigint DEFAULT '0',
  `previous_mint` bigint DEFAULT '0',
  `delta_mint` bigint DEFAULT '0',
  `old_previous_mint` bigint DEFAULT NULL,
  `current_wallets` bigint DEFAULT '0',
  `previous_wallets` bigint DEFAULT '0',
  `delta_wallets` bigint DEFAULT '0',
  `old_previous_wallets` bigint DEFAULT '0',
  `alert_count` int DEFAULT '0',
  `mint_alert_count` int DEFAULT '0',
  `wallet_alert_count` int DEFAULT '0',
  `average_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `current_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `total_mints` bigint DEFAULT '0',
  `mint_wallet_ratio` int DEFAULT '0',
  `previous_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `ethervalue` decimal(33,21) DEFAULT '0.000000000000000000000',
  `txn_fee` decimal(33,21) DEFAULT '0.000000000000000000000',
  `owner_count` int DEFAULT '0',
  `trending_reported` tinyint DEFAULT '0',
  `bot` tinyint DEFAULT '0',
  `bot_mint` tinyint DEFAULT '0',
  `bot_wallet` tinyint DEFAULT '0',
  `first_alert` timestamp NULL DEFAULT NULL,
  `last_alert` timestamp NULL DEFAULT NULL,
  `last_mint_alert` timestamp NULL DEFAULT NULL,
  `last_wallet_alert` timestamp NULL DEFAULT NULL,
  `last_updated` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`contract_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mint_tracker_alertlog` (
  `contract_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `metadata_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `current_mint` bigint DEFAULT '0',
  `previous_mint` bigint DEFAULT '0',
  `delta_mint` bigint DEFAULT '0',
  `old_previous_mint` bigint DEFAULT NULL,
  `current_wallets` bigint DEFAULT '0',
  `previous_wallets` bigint DEFAULT '0',
  `delta_wallets` bigint DEFAULT '0',
  `old_previous_wallets` bigint DEFAULT '0',
  `alert_count` int DEFAULT '0',
  `mint_alert_count` int DEFAULT '0',
  `wallet_alert_count` int DEFAULT '0',
  `average_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `current_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `total_mints` bigint DEFAULT '0',
  `mint_wallet_ratio` int DEFAULT '0',
  `previous_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `ethervalue` decimal(33,21) DEFAULT '0.000000000000000000000',
  `txn_fee` decimal(33,21) DEFAULT '0.000000000000000000000',
  `owner_count` int DEFAULT '0',
  `trending_reported` tinyint DEFAULT '0',
  `bot` tinyint DEFAULT '0',
  `bot_mint` tinyint DEFAULT '0',
  `bot_wallet` tinyint DEFAULT '0',
  `reported` tinyint(1) DEFAULT '0',
  `first_alert` timestamp NULL DEFAULT NULL,
  `last_alert` timestamp NULL DEFAULT NULL,
  `last_mint_alert` timestamp NULL DEFAULT NULL,
  `last_wallet_alert` timestamp NULL DEFAULT NULL,
  `last_updated` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `mint_tracker_trending` (
  `id` int NOT NULL AUTO_INCREMENT,
  `contract_address` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_owner` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `token_uri` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `opensea_image_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `metadata_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `total_mints` bigint DEFAULT '0',
  `total_wallets` bigint DEFAULT '0',
  `alert_count` int DEFAULT '0',
  `wallet_alert_count` int DEFAULT '0',
  `mint_alert_count` int DEFAULT '0',
  `average_price` decimal(33,21) DEFAULT '0.000000000000000000000',
  `owner_count` int DEFAULT '0',
  `bot_mint` tinyint DEFAULT '0',
  `bot_wallet` tinyint DEFAULT '0',
  `reported` tinyint(1) DEFAULT '0',
  `last_updated` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=132396 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `verified_contracts` (
  `contract_address` varchar(45) NOT NULL,
  `owner_address` varchar(45) DEFAULT NULL,
  `contract_name` varchar(256) DEFAULT NULL,
  `symbol` varchar(45) DEFAULT NULL,
  `balance` decimal(26,4) DEFAULT NULL,
  `token` int NOT NULL,
  `diff_status` int DEFAULT NULL,
  `filtered` varchar(45) DEFAULT NULL,
  `filter_reason` varchar(256) DEFAULT NULL,
  `bot` int NOT NULL,
  `telebot` int NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`contract_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

